language: node_js
node_js: '8'

branches:
  only:
  - master
  - 01-basic-web
  - 02-webpack-parcel
  - 03-travis-ci

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run parcel:build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: dist
  verbose: true
  on:
    branch: 03-travis-ci